spring.application.name=medichain

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/medichain
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate,dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

blockchain.rpc-url=http://127.0.0.1:7545
blockchain.wallet-private-key=0x911f157d57fdc49dbeb8e0cacb250843e6aa9519620cb9deb6598eb8d3f969c3
blockchain.gas-price=20000000000
blockchain.gas-limit=6000000
blockchain.supply-chain.contract-address=0xa7aB8bC729c4C9a8CC40352978c9669A22a2Dfc5
blockchain.tx-receipt.poll-interval-ms=1000
blockchain.tx-receipt.max-attempts=40